---
title: "More EDA"
author: "Shane Hauck"
date: "2023-11-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(gganimate)
theme_set(theme_bw())

library(sportyR)
field_params <- list(
  field_apron = "springgreen3",
  field_border = "springgreen3",
  offensive_endzone = "springgreen3",
  defensive_endzone = "springgreen3",
  offensive_half = "springgreen3",
  defensive_half = "springgreen3"
)

nfl_field <- function(xlims) {
  geom_football(
    league = "nfl",
    display_range = "full",
    x_trans = 60,
    y_trans = 26.6667,
    xlims = xlims,
    color_updates = field_params
  )
}
```


```{r}
players <- read_csv("data/players.csv")
plays <- read_csv("data/plays.csv")
tracking_week_2 <- read_csv("data/tracking_week_2.csv") %>%
  mutate(
    # make all plays go from left to right
    x = ifelse(playDirection == "left", 120 - x, x),
    y = ifelse(playDirection == "left", 160 / 3 - y, y),
    # flip player direction and orientation
    dir = ifelse(playDirection == "left", dir + 180, dir),
    dir = ifelse(dir > 360, dir - 360, dir),
    o = ifelse(playDirection == "left", o + 180, o),
    o = ifelse(o > 360, o - 360, o)
  )

focused_df <- left_join(tracking_week_2, plays) %>%
  left_join(players) %>%
  select(
    gameId, playId, nflId, position, frameId, x, y, s, a, dis, o, dir, event,
    playDescription, ballCarrierId, club, possessionTeam, defensiveTeam,
    playResult, playNullifiedByPenalty, offenseFormation, defendersInTheBox,
    expectedPoints, expectedPointsAdded
  )
```


```{r}
# Keep plays where a snap occurs (see kaggle for description of designed rushes)
snapped_plays <- focused_df %>%
  filter(event == "ball_snap") %>%
  distinct(gameId, playId) %>%
  left_join(focused_df)

# Filter out any quick passing plays
designed_runs <- snapped_plays %>%
  filter(event %in% c("run", "lateral", "handoff")) %>%
  distinct(gameId, playId) %>%
  left_join(snapped_plays)

# Accurately removed passing plays that included a snap of the ball
snapped_plays %>%
  filter(event == "pass_forward") %>%
  distinct(gameId, playId) %>%
  nrow()
```


```{r}
# Add variable for the section of the field where the play went and playside
designed_runs <- designed_runs %>%
  mutate(wherePlayWent = str_extract(playDescription, "(left|right|up the) (guard|tackle|end|middle)")) %>%
  mutate(ballY_preSnap = ifelse(frameId == 5 & club == "football", y, NA)) %>%
  group_by(gameId, playId) %>%
  fill(ballY_preSnap, .direction = c("updown")) %>%
  mutate(ballCarrierY = ifelse(nflId == ballCarrierId, y, NA)) %>%
  fill(ballCarrierY, .direction = c("updown"))

# plays where all offensive lineman and running backs take same same first step
sameDir <- designed_runs %>%
  filter(position %in% c("T", "G", "C") | nflId == ballCarrierId) %>%
  group_by(gameId, playId, nflId) %>%
  mutate(ball_snap_y = ifelse(frameId == 5, y, NA)) %>%
  fill(ball_snap_y, .direction = "updown") %>%
  mutate(frame_7_y = ifelse(frameId == 7, y, NA)) %>%
  fill(frame_7_y, .direction = "updown") %>%
  mutate(y_change = frame_7_y - ball_snap_y) %>%
  mutate(dir_atSnap = ifelse(y_change > 0, "left", "right")) %>%
  group_by(gameId, playId) %>%
  mutate(same_dir = ifelse(all(dir_atSnap == first(dir_atSnap)), "yes", "no")) %>%
  distinct(gameId, playId, same_dir)

# plays where all offensive lineman and running backs take same same first step
sameDir_yes <- sameDir %>%
  filter(same_dir == "yes") %>%
  distinct(gameId, playId)

```


```{r}
DL_info <- designed_runs %>%
  filter(club == defensiveTeam | club == "football") %>%
  group_by(gameId, playId) %>%
  # Identifying the frame before the ball snap
  mutate(pre_ball_snap_frame = ifelse(event == "ball_snap", frameId - 1, NA)) %>%
  fill(pre_ball_snap_frame, .direction = "updown") %>%
  filter(frameId == pre_ball_snap_frame) %>%
  # Assigning ball position
  mutate(
    ball_x = ifelse(club == "football", x, NA),
    ball_y = ifelse(club == "football", y, NA)
  ) %>%
  fill(ball_x, ball_y, .direction = "updown") %>%
  filter(club != "football") %>%
  # Calculating distances and determining if defenders are in the box and on the LOS
  mutate(
    distance_to_ball = sqrt((x - ball_x)^2 + (y - ball_y)^2),
    rank_distance_to_ball = rank(distance_to_ball),
    isInBox = ifelse(rank_distance_to_ball <= defendersInTheBox, "yes", "no"),
    distance_to_LOS = abs(x - ball_x),
    isonLOS = ifelse(distance_to_LOS <= 2, "yes", "no")
  ) %>%
  select(gameId, playId, nflId, pre_ball_snap_frame, isInBox, isonLOS)


processing <- right_join(DL_info, designed_runs %>% group_by(gameId, playId, nflId) %>%
  mutate(ball_snap_y = ifelse(frameId == 5, y, NA)) %>%
  fill(ball_snap_y, .direction = "updown") %>%
  mutate(frame_7_y = ifelse(frameId == 7, y, NA)) %>%
  fill(frame_7_y, .direction = "updown") %>%
  mutate(y_change = frame_7_y - ball_snap_y) %>%
  mutate(dir_atSnap = ifelse(y_change > 0, "left", "right")) %>%
  group_by(gameId, playId) %>%
  mutate(same_dir = ifelse(all(dir_atSnap == first(dir_atSnap)), "yes", "no"))) %>%
  mutate(
    isInBox = ifelse(is.na(isInBox), "no", isInBox),
    isonLOS = ifelse(is.na(isonLOS), "no", isonLOS)
  ) %>%
  fill(pre_ball_snap_frame, .direction = c("updown")) %>%
  filter(frameId == pre_ball_snap_frame) %>%
  filter(club == possessionTeam |
    (isInBox == "yes" & isonLOS == "yes")) %>%
  filter(club != possessionTeam |
    position %in% c("T", "G", "C") |
    nflId == ballCarrierId) %>%
  mutate(isOLM = ifelse(position %in% c("T", "G", "C"), 1, 0)) %>%
  group_by(gameId, playId) %>%
  mutate(
    numOLM = sum(isOLM),
    numOLM = ifelse(numOLM == 0, max(numOLM), numOLM)
  ) %>%
  filter(numOLM > 0) %>%
  mutate(numonLOSInBox = sum(isonLOS == "yes" & isInBox == "yes")) %>%
  distinct(gameId, playId, nflId, isInBox, isonLOS, numOLM, numonLOSInBox) %>%
  mutate(
    OLM_outnumbered = ifelse(numOLM <= numonLOSInBox, "yes", "no"),
    OLM_upby = numOLM - numonLOSInBox
  ) %>%
  left_join(sameDir) %>%
  mutate(same_dir_exception = ifelse(same_dir == "no" & OLM_outnumbered == "no", "yes", "no")) %>%
  right_join(designed_runs) %>%
  filter(same_dir_exception == "yes") %>%
  filter(position %in% c("T", "G", "C") |
    nflId == ballCarrierId) %>%
  mutate(ball_snap_frame = ifelse(event == "ball_snap", frameId, NA)) %>%
  fill(ball_snap_frame, .direction = c("updown")) %>%
  filter(frameId %in% c(ball_snap_frame)) %>%
  mutate(dir_atSnap = ifelse(dir >= 180, "left", "right")) %>%
  # Count the number of players who went right and who went left
  group_by(gameId, playId) %>%
  mutate(
    numLeft = sum(dir_atSnap == "left"),
    numRight = sum(dir_atSnap == "right")
  ) %>%
  # Find the direction that the minority of players went
  mutate(minorityDir = ifelse(numLeft < numRight, "left", "right")) %>%
  mutate(ballCarrier_majorityDir = ifelse(nflId == ballCarrierId & dir_atSnap == minorityDir, "no", "yes")) %>%
  # apply ballCarrier_majorityDir to all players for game and play
  group_by(gameId, playId) %>%
  mutate(ballCarrier_majorityDir = ifelse(any(ballCarrier_majorityDir == "yes"), "yes", "no")) %>%
  filter(ballCarrier_majorityDir == "yes") %>%
  filter(nflId != ballCarrierId) %>%
  # Count the number of players that went the minority direction
  mutate(
    numMinorityDir = ifelse(minorityDir == "left", numLeft, numRight),
    wentMinority = ifelse(dir_atSnap == minorityDir, "yes", "no")
  ) %>%
  filter(numMinorityDir == OLM_upby) %>%
  select(gameId, playId, nflId, position, x, y, club, possessionTeam, wherePlayWent, dir_atSnap, minorityDir, wentMinority)

all_LM <- left_join(DL_info, designed_runs) %>%
  mutate(ball_snap_frame = ifelse(event == "ball_snap", frameId, NA)) %>%
  fill(ball_snap_frame, .direction = c("updown")) %>%
  filter(frameId %in% c(ball_snap_frame)) %>%
  filter(isInBox == "yes" & isonLOS == "yes") %>%
  select(gameId, playId, nflId, position, x, y, club, possessionTeam, wherePlayWent) %>%
  rbind(processing) %>%
  group_by(gameId, playId) %>%
  filter(sum(wentMinority == "yes", na.rm = T) <= 1)


# Define the sideline values
left_sideline_y <- 53.3
right_sideline_y <- 0

# Function to find the nearest offensive lineman or sideline in the direction of the play
find_nearest_ol_or_sideline <- function(ol_row, ol_df) {
  if (ol_row$minorityDir == "right") {
    nearest_ol <- ol_df %>%
      filter(gameId == ol_row$gameId, playId == ol_row$playId, nflId != ol_row$nflId, y > ol_row$y) %>%
      arrange(y) %>%
      slice(1) %>%
      pull(y)
    return(ifelse(length(nearest_ol) == 0, left_sideline_y, nearest_ol))
  } else {
    nearest_ol <- ol_df %>%
      filter(gameId == ol_row$gameId, playId == ol_row$playId, nflId != ol_row$nflId, y < ol_row$y) %>%
      arrange(desc(y)) %>%
      slice(1) %>%
      pull(y)
    return(ifelse(length(nearest_ol) == 0, right_sideline_y, nearest_ol))
  }
}

# Function to check for a defender in the gap
is_defender_in_gap <- function(ol_row, ol_df, def_df) {
  nearest_ol_y <- find_nearest_ol_or_sideline(ol_row, ol_df)
  gap_min_y <- min(ol_row$y, nearest_ol_y)
  gap_max_y <- max(ol_row$y, nearest_ol_y)

  any_defender_in_gap <- any(
    def_df$gameId == ol_row$gameId &
      def_df$playId == ol_row$playId &
      def_df$y >= gap_min_y &
      def_df$y <= gap_max_y
  )

  return(any_defender_in_gap)
}

# Apply the function to the offensive linemen who went in the minority direction
ol_df <- all_LM %>% filter(position %in% c("T", "G", "C"))
def_df <- all_LM %>% filter(!(position %in% c("T", "G", "C")))
ol_minority_df <- all_LM %>% filter(wentMinority == "yes")

ol_minority_df <- ol_minority_df %>%
  rowwise() %>%
  mutate(defenderInGap = is_defender_in_gap(cur_data_all(), ol_df, def_df)) %>%
  ungroup() 

ol_tracking_data <- ol_minority_df %>%
  group_by(gameId, playId) %>%
  mutate(all_defenderInGap = all(defenderInGap == FALSE)) %>%
  filter(all_defenderInGap == TRUE) %>%
  distinct(gameId, playId) %>%
  left_join(all_LM) %>%
  filter(club == possessionTeam) %>%
  distinct(gameId, playId, nflId, wentMinority) %>%
  left_join(designed_runs, by = c("gameId", "playId", "nflId")) %>%
  left_join(ol_minority_df %>% distinct(gameId, nflId, defenderInGap)) %>%
  mutate(defenderInGap = ifelse(is.na(defenderInGap), TRUE, FALSE)) %>%
  distinct(gameId, playId, nflId, frameId, .keep_all = TRUE)

dl_tracking_data <- all_LM %>%
  filter(club != possessionTeam) %>%
  distinct(gameId, playId, nflId) %>%
  left_join(right_join(designed_runs, ol_tracking_data %>% distinct(gameId, playId)))

# Lineman tracking data for plays where a player went minority direction and had no defender in the gap
lm_tracking_data <- rbind(ol_tracking_data, dl_tracking_data) %>% filter(!is.na(frameId))


ol_questionPlayer_td <- ol_tracking_data %>%
  filter(wentMinority == "yes" & defenderInGap == FALSE) %>%
  distinct(gameId, playId, nflId, frameId, .keep_all = TRUE)

count_passed_players <- function(player_id, player_gameId, player_playId, all_players_data) {
  # Select the player's data from all_players_data
  player_data <- all_players_data[
    all_players_data$gameId == player_gameId &
      all_players_data$playId == player_playId,
  ]

  # Determine the frame range to check
  frames_to_check <- 5:20
  passed_players_ids <- numeric()

  for (frame in frames_to_check[-length(frames_to_check)]) {
    current_frame_data <- player_data[player_data$frameId == frame, ]
    next_frame_data <- player_data[player_data$frameId == frame + 1, ]

    # Ensure that we have data for the current and next frames
    if (nrow(current_frame_data) != 0 && nrow(next_frame_data) != 0) {
      player_current_frame <- player_data[player_data$frameId == frame &
        player_data$nflId == player_id, ]
      other_players_current_frame <- player_data[player_data$frameId == frame &
        player_data$nflId != player_id, ]
      player_next_frame <- player_data[player_data$frameId == frame + 1 &
        player_data$nflId == player_id, ]
      other_players_next_frame <- player_data[player_data$frameId == frame + 1 &
        player_data$nflId != player_id, ]
      # Logic to determine if players were passed, based on direction and y coordinate changes
      if (player_next_frame$x - player_current_frame$x > 0) {
        # Passed if y coordinate goes from greater to lesser
        passed_this_frame <- other_players_current_frame[other_players_current_frame$y > player_current_frame$y &
          other_players_next_frame$y < player_next_frame$y &
            other_players_current_frame$x > player_current_frame$x &
            other_players_next_frame$x > player_next_frame$x, ]$nflId
      } else {
        # Passed if y coordinate goes from lesser to greater
        passed_this_frame <- other_players_current_frame[other_players_current_frame$y < player_current_frame$y &
          other_players_next_frame$y > player_next_frame$y &
            other_players_current_frame$x > player_current_frame$x &
            other_players_next_frame$x > player_next_frame$x, ]$nflId
      }

      # Update the vector of passed players
      passed_players_ids <- unique(c(passed_players_ids, passed_this_frame))
    }
  }

  return(length(passed_players_ids))
}


notPulling <- ol_questionPlayer_td %>%
  group_by(gameId, playId, nflId) %>%
  summarise(passedCount = count_passed_players(nflId, gameId, playId, ol_tracking_data)) %>%
  filter(passedCount == 0) %>%
  distinct(gameId, playId)
```


```{r}
valid_plays <- rbind(sameDir_yes, notPulling)

WK2_SameDirection_TrackData <- left_join(valid_plays, designed_runs) %>% filter(!wherePlayWent %in% c("left end", "right end"))

WK2_SameDirection_TrackData %>% distinct(gameId, playId) %>% nrow()
```


# USE WK2_SameDirection_TrackData for analysis of week 2, save the data set

```{r}
# Save dataframe as CSV
write.csv(WK2_SameDirection_TrackData, file = "data/WK2_SameDirection_TrackData.csv", row.names = FALSE)
```

# Example intersection
```{r eval=FALSE, include=FALSE}
  # Calculate the slope and intercept of the line passing through the start and end points of the ball
splitdata <- splitdata %>% 
    mutate(slope = (BallY_2 - BallY_1) / (BallX_2 - BallX_1),
           intercept = BallY_1 - slope * BallX_1)
  
 
  
  # Check if there are two players with different y-coordinates for the same x-coordinate
splitdata <- splitdata %>% group_by(GameEventID) %>%
  mutate(splits_players = any((BallX_1 < PlayerX & BallX_2 > PlayerX &
                                    slope * PlayerX + intercept < max(PlayerY) &
                                    slope * PlayerX + intercept > min(PlayerY)) |
                                   (BallX_1 > PlayerX & BallX_2 < PlayerX &
                                      slope * PlayerX + intercept < max(PlayerY) &
                                      slope * PlayerX + intercept > min(PlayerY))
))

# Returns boolean for whether the ball splits the players
# I think this can work if you have a dataset with only ball carriers and offensive linemen
```





```{r}
ggplot(all_LM %>% filter(gameId == 2022091804, playId == 881), aes(x = x, y = y, color = club)) +
  geom_point()
```



```{r}
test_run <- designed_runs %>% filter(gameId == 2022091500, playId == 1983)
nfl_field(c(0, 120)) +
  geom_point(
    data = test_run, aes(x = x, y = y, color = club),
    show.legend = FALSE,
    size = 2
  ) +
  geom_point(data = test_run %>% filter(nflId == 47874), aes(x = x, y = y), color = "black") +
  geom_point(data = test_run %>% filter(nflId == 53442), aes(x = x, y = y), color = "black") +
  transition_time(frameId) +
  scale_color_manual(values = c("purple", "yellow", "white"))
```
