---
title: "Tables"
author: "Shane Hauck, Marion Haney"
date: "2024-01-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
```

```{r}
BC_ES_data <- read_csv("data/BC_and_ES_information.csv") %>% select(-1)
players <- read_csv("data/players.csv")

tables_df <- left_join(BC_ES_data, players %>% select(nflId, position, displayName), by = c("ballCarrierId" = "nflId")) %>%
  rename(BC_position = position, BC_name = displayName) %>%
  left_join(players %>% select(nflId, position, displayName), by = c("edgeSetterId_atMaxChange" = "nflId")) %>%
  rename(ES_position = position, ES_name = displayName) 
```


# Making tables for the Shiny app Offense view

## Team Offense View

We want to show the mean EPA and frequency for the team's performance on 
inside zone run plays, specifically bounces, dives, and cutbacks.

We define bounces, dives, and cutbacks using relative_total_change:
Cutback: < -30, -10)
Dive: -10, 10)
Bounce: 10, > 30

Table data needed: team, type, frequency, meanEPA

```{r}
play_types <- c("Cutback", "Dive", "Bounce")
ranges <- c(-45, -10, 10, 40)
type_freq <- table(play_types)

team_table_df <- tables_df %>%
  # Make a column for play type: type
  mutate(type = cut(relative_total_change, breaks = ranges, 
                    labels = play_types, include.lowest = TRUE)) %>%
  # We want frequency at the play side level: for left and right
  group_by(possessionTeam, playSide) %>%
  mutate(n_plays = n()) %>%
  group_by(possessionTeam, playSide, type) %>%
  mutate(n_plays_type = n()) %>%
  # Make column for play type frequency: freq
  mutate(freq = n_plays_type / n_plays)

team_table_df <- team_table_df %>%
  # Make column for mean EPA for each team's play type on left and right
  group_by(possessionTeam, type, playSide) %>%
  mutate(meanEPA = mean(expectedPointsAdded)) %>%
  # Select only columns we need
  select(possessionTeam, playSide, type, n_plays, n_plays_type, freq, meanEPA)

team_table_df <- unique(team_table_df) %>% arrange(possessionTeam, playSide, type)
```

## Player Offense View


